[package]
name = "solarhorizon/immut"
description = "Immutable data library"
authors = ["SolarHorizon"]
version = "0.4.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

